name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build and Push
    strategy:
    matrix:
      os: [ubuntu-latest, macos-latest]
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build
        run: mkdir build/${{ matrix.os }}
        run: mv disk-analyzer build/${{ matrix.os }}
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
